// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppEigen.h>
#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// ensemble_mcmc_R
Rcpp::List ensemble_mcmc_R(Rcpp::List Y, int J, int num_chains, int chain_length, int thinning, bool empirical, int burn_in, bool quadratic, int iter_update, double beta_mean, double alpha_mu_2, double adaptive_prop, bool print_progress, int num_cores, bool save_only_z, bool use_sparse_prior, bool use_spike_slab, bool use_reg_horseshoe, double p_0, Rcpp::NumericVector baynorm_mu_estimate, Rcpp::NumericVector baynorm_phi_estimate, Rcpp::List baynorm_beta_list);
RcppExport SEXP _normHDPcpp_ensemble_mcmc_R(SEXP YSEXP, SEXP JSEXP, SEXP num_chainsSEXP, SEXP chain_lengthSEXP, SEXP thinningSEXP, SEXP empiricalSEXP, SEXP burn_inSEXP, SEXP quadraticSEXP, SEXP iter_updateSEXP, SEXP beta_meanSEXP, SEXP alpha_mu_2SEXP, SEXP adaptive_propSEXP, SEXP print_progressSEXP, SEXP num_coresSEXP, SEXP save_only_zSEXP, SEXP use_sparse_priorSEXP, SEXP use_spike_slabSEXP, SEXP use_reg_horseshoeSEXP, SEXP p_0SEXP, SEXP baynorm_mu_estimateSEXP, SEXP baynorm_phi_estimateSEXP, SEXP baynorm_beta_listSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::List >::type Y(YSEXP);
    Rcpp::traits::input_parameter< int >::type J(JSEXP);
    Rcpp::traits::input_parameter< int >::type num_chains(num_chainsSEXP);
    Rcpp::traits::input_parameter< int >::type chain_length(chain_lengthSEXP);
    Rcpp::traits::input_parameter< int >::type thinning(thinningSEXP);
    Rcpp::traits::input_parameter< bool >::type empirical(empiricalSEXP);
    Rcpp::traits::input_parameter< int >::type burn_in(burn_inSEXP);
    Rcpp::traits::input_parameter< bool >::type quadratic(quadraticSEXP);
    Rcpp::traits::input_parameter< int >::type iter_update(iter_updateSEXP);
    Rcpp::traits::input_parameter< double >::type beta_mean(beta_meanSEXP);
    Rcpp::traits::input_parameter< double >::type alpha_mu_2(alpha_mu_2SEXP);
    Rcpp::traits::input_parameter< double >::type adaptive_prop(adaptive_propSEXP);
    Rcpp::traits::input_parameter< bool >::type print_progress(print_progressSEXP);
    Rcpp::traits::input_parameter< int >::type num_cores(num_coresSEXP);
    Rcpp::traits::input_parameter< bool >::type save_only_z(save_only_zSEXP);
    Rcpp::traits::input_parameter< bool >::type use_sparse_prior(use_sparse_priorSEXP);
    Rcpp::traits::input_parameter< bool >::type use_spike_slab(use_spike_slabSEXP);
    Rcpp::traits::input_parameter< bool >::type use_reg_horseshoe(use_reg_horseshoeSEXP);
    Rcpp::traits::input_parameter< double >::type p_0(p_0SEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type baynorm_mu_estimate(baynorm_mu_estimateSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type baynorm_phi_estimate(baynorm_phi_estimateSEXP);
    Rcpp::traits::input_parameter< Rcpp::List >::type baynorm_beta_list(baynorm_beta_listSEXP);
    rcpp_result_gen = Rcpp::wrap(ensemble_mcmc_R(Y, J, num_chains, chain_length, thinning, empirical, burn_in, quadratic, iter_update, beta_mean, alpha_mu_2, adaptive_prop, print_progress, num_cores, save_only_z, use_sparse_prior, use_spike_slab, use_reg_horseshoe, p_0, baynorm_mu_estimate, baynorm_phi_estimate, baynorm_beta_list));
    return rcpp_result_gen;
END_RCPP
}
// normHDP_mcmc_fixed_z
Rcpp::List normHDP_mcmc_fixed_z(const std::vector<Eigen::MatrixXd>& Y, const std::vector<std::vector<int>>& cluster_estimates, int number_iter, int thinning, bool empirical, int burn_in, bool quadratic, int iter_update, double beta_mean, double alpha_mu_2, double adaptive_prop, int num_cores, SEXP baynorm_mu_estimate, SEXP baynorm_phi_estimate, SEXP baynorm_beta, bool use_horseshoe, bool use_reg_horseshoe, bool use_spike_slab, double horseshoe_p0);
RcppExport SEXP _normHDPcpp_normHDP_mcmc_fixed_z(SEXP YSEXP, SEXP cluster_estimatesSEXP, SEXP number_iterSEXP, SEXP thinningSEXP, SEXP empiricalSEXP, SEXP burn_inSEXP, SEXP quadraticSEXP, SEXP iter_updateSEXP, SEXP beta_meanSEXP, SEXP alpha_mu_2SEXP, SEXP adaptive_propSEXP, SEXP num_coresSEXP, SEXP baynorm_mu_estimateSEXP, SEXP baynorm_phi_estimateSEXP, SEXP baynorm_betaSEXP, SEXP use_horseshoeSEXP, SEXP use_reg_horseshoeSEXP, SEXP use_spike_slabSEXP, SEXP horseshoe_p0SEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const std::vector<Eigen::MatrixXd>& >::type Y(YSEXP);
    Rcpp::traits::input_parameter< const std::vector<std::vector<int>>& >::type cluster_estimates(cluster_estimatesSEXP);
    Rcpp::traits::input_parameter< int >::type number_iter(number_iterSEXP);
    Rcpp::traits::input_parameter< int >::type thinning(thinningSEXP);
    Rcpp::traits::input_parameter< bool >::type empirical(empiricalSEXP);
    Rcpp::traits::input_parameter< int >::type burn_in(burn_inSEXP);
    Rcpp::traits::input_parameter< bool >::type quadratic(quadraticSEXP);
    Rcpp::traits::input_parameter< int >::type iter_update(iter_updateSEXP);
    Rcpp::traits::input_parameter< double >::type beta_mean(beta_meanSEXP);
    Rcpp::traits::input_parameter< double >::type alpha_mu_2(alpha_mu_2SEXP);
    Rcpp::traits::input_parameter< double >::type adaptive_prop(adaptive_propSEXP);
    Rcpp::traits::input_parameter< int >::type num_cores(num_coresSEXP);
    Rcpp::traits::input_parameter< SEXP >::type baynorm_mu_estimate(baynorm_mu_estimateSEXP);
    Rcpp::traits::input_parameter< SEXP >::type baynorm_phi_estimate(baynorm_phi_estimateSEXP);
    Rcpp::traits::input_parameter< SEXP >::type baynorm_beta(baynorm_betaSEXP);
    Rcpp::traits::input_parameter< bool >::type use_horseshoe(use_horseshoeSEXP);
    Rcpp::traits::input_parameter< bool >::type use_reg_horseshoe(use_reg_horseshoeSEXP);
    Rcpp::traits::input_parameter< bool >::type use_spike_slab(use_spike_slabSEXP);
    Rcpp::traits::input_parameter< double >::type horseshoe_p0(horseshoe_p0SEXP);
    rcpp_result_gen = Rcpp::wrap(normHDP_mcmc_fixed_z(Y, cluster_estimates, number_iter, thinning, empirical, burn_in, quadratic, iter_update, beta_mean, alpha_mu_2, adaptive_prop, num_cores, baynorm_mu_estimate, baynorm_phi_estimate, baynorm_beta, use_horseshoe, use_reg_horseshoe, use_spike_slab, horseshoe_p0));
    return rcpp_result_gen;
END_RCPP
}
// rcpp_hello_world
List rcpp_hello_world();
RcppExport SEXP _normHDPcpp_rcpp_hello_world() {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    rcpp_result_gen = Rcpp::wrap(rcpp_hello_world());
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_normHDPcpp_ensemble_mcmc_R", (DL_FUNC) &_normHDPcpp_ensemble_mcmc_R, 22},
    {"_normHDPcpp_normHDP_mcmc_fixed_z", (DL_FUNC) &_normHDPcpp_normHDP_mcmc_fixed_z, 19},
    {"_normHDPcpp_rcpp_hello_world", (DL_FUNC) &_normHDPcpp_rcpp_hello_world, 0},
    {NULL, NULL, 0}
};

RcppExport void R_init_normHDPcpp(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
