# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

ensemble_mcmc_R <- function(Y, J, num_chains, chain_length, thinning, empirical, burn_in, quadratic, iter_update, beta_mean, alpha_mu_2, adaptive_prop, print_progress, num_cores, baynorm_mu_estimate, baynorm_phi_estimate, baynorm_beta_list) {
    .Call(`_normHDPcpp_ensemble_mcmc_R`, Y, J, num_chains, chain_length, thinning, empirical, burn_in, quadratic, iter_update, beta_mean, alpha_mu_2, adaptive_prop, print_progress, num_cores, baynorm_mu_estimate, baynorm_phi_estimate, baynorm_beta_list)
}

normHDP_mcmc_fixed_z <- function(Y, cluster_estimates, number_iter, thinning = 5L, empirical = TRUE, burn_in = 3000L, quadratic = FALSE, iter_update = 100L, beta_mean = 0.06, alpha_mu_2 = -1.0, adaptive_prop = 0.1, num_cores = 1L, baynorm_mu_estimate = NULL, baynorm_phi_estimate = NULL, baynorm_beta = NULL) {
    .Call(`_normHDPcpp_normHDP_mcmc_fixed_z`, Y, cluster_estimates, number_iter, thinning, empirical, burn_in, quadratic, iter_update, beta_mean, alpha_mu_2, adaptive_prop, num_cores, baynorm_mu_estimate, baynorm_phi_estimate, baynorm_beta)
}

rcpp_hello_world <- function() {
    .Call(`_normHDPcpp_rcpp_hello_world`)
}

